### ISSUE TITLE
qml-runner registers its LS2 service using app's LS2 service name: why? 

### ISSUE THREAD

**Issue by Tofee** [webosose/qml-webos-framework#1]
Hi !

The commit https://github.com/webosose/qml-webos-framework/commit/494c3fe267c67cde7d20d921c70d7b89ff806537 seems to have introduced a minor issue: with this change, any QML developper will need to include the permission for the group "applications", because qml-runner calls applicationManager in LunaServiceWrapper::subscribe(). It's even described in the [documentation](https://www.webosose.org/docs/tutorials/qml-apps/developing-built-in-qml-apps/#step-2-configure-the-qml-app).

However I don't see the benefit of this change: if qml-runner would use its own name for its own calls, then "applications" permission could be granted for qml-runner itself, for all applications. And the rest of the client application calls would still be done on the ApplicationService of the app, i.e. with their own permissions setup.

And actually, we see that it worked that way before this commit: in https://github.com/webosose/qml-webos-framework/blob/master/tools/runner/sysbus/com.webos.app.qmlrunner.perm.json the permission is still here.

On the same topic, it is surprising that LS2_NAME isn't used at all by qml-webos-bridge (see https://github.com/webosose/qml-webos-bridge/blob/master/plugin/lunaservicemgr.cpp#L132 for instance, where we see it rebuilds the application service name the same way SAM does, but without using the available LS2_NAME env variable set by SAM)

It could be I missed the point, but in this case I'm curious to know why it was changed this way.

**Comment by jaeyoonjung** [comment]
Hi,

Thanks for your comment.

The main reason of the introduction of LS2_NAME environment variable is to allow multiple instances of the same application. In case multiple instances of the same application are running they need to use different LS2 names as otherwise they conflict and fail to register.

The permission setup should be done per application. com.webos.app.qmlrunner.perm.json has existed for convenience. 
"applications" is the one of groups needed for all native applications since they need to register themselves to SAM to get notified some lifecycle events.

Hope this answers your question.

**Comment by Tofee** [comment]
Thanks for your explanations, I understand better the rational behind all this.
